### ISSUE TITLE
dogm 'города'

### ISSUE THREAD

**Issue by Ferri0** [IgorAleks88/rsclone#71]
If activate dogm and affected player don't have enough stone resourse - dogm take 1 action point but nothing happen.

Dogm should don't take action point and throw error message if affected player don't have enough stone

**Comment by DenisOleksiuk** [comment]
are you thinking?
I don't think so, but maybe you right

**Comment by Ferri0** [comment]
https://i.postimg.cc/4NrGFhcn/screenshot-45.png - before dogm activation
https://i.postimg.cc/fWPQJ0B5/screenshot-46.png - after dogm activation
