### ISSUE TITLE
dogm - 'Свод законов'

### ISSUE THREAD

**Issue by DenisOleksiuk** [IgorAleks88/rsclone#74]
when I used this card
![image](https://user-images.githubusercontent.com/66439220/105968279-8b625800-608f-11eb-8e08-dc31a5c77e27.png)

nothing happening, but dogma take 1 active point

![image](https://user-images.githubusercontent.com/66439220/105968502-d4b2a780-608f-11eb-9873-3a3fbe572936.png)

**Comment by Ferri0** [comment]
Its text from my issue #71, i don't understand problem.

**Comment by DenisOleksiuk** [comment]
yes I did  copy / paste :), because this domga - 'Свод законов' has the same problem

**Comment by Ferri0** [comment]
![C47055E0-668E-45EB-BBFA-7032A90038DE](https://user-images.githubusercontent.com/67440994/105966764-bf3c7e00-608d-11eb-8576-b1c7b8d7471c.jpeg)

still don't understand, there is no stone or resources requirements on this card

**Comment by DenisOleksiuk** [comment]
a sorry, this dogma just takes away the action point, and does not work
