### ISSUE TITLE
Fix load game feature

### ISSUE THREAD

**Issue by Ferri0** [IgorAleks88/rsclone#94]
Add this to load game. This should hide all players containers in header and then you should display needed amount.
  For example if you save game on 2 players then start new game on 3 players and load previous game - in header 3 players blocks will be left, but loaded game will works only for 2 players (how its should be)

  
  [...document.querySelectorAll('.player-container')].forEach((playerBlock) => {
    playerBlock.classList.add('player-container__hidden');
  });

**Comment by DenisOleksiuk** [comment]
done
